const filteredCategories = [
    'electronic',
    'rock',
    'romance',
    'party',
    'k-pop',
    'indie',
    'workout',
    'chill',
    'jazz',
    'gaming',
    'metal',
    'classical',
    'country',
    'punk',
    'pop',
    'acoustic',
    'anime',
    'rap',
    'hip-hop',
    'indian'
    
]


const categories = [
    [ 'acoustic', 'acoustic' ,null ],
    [ 'afrobeat', 'party' ,null ],
    [ 'alt-rock', 'rock' ,null ],
    [ 'alternative', 'rock' , null ],
    [ 'ambient','chill' , null ],
    [ 'anime', 'anime' ,null ],
    [ 'black-metal', 'metal' , null ],
    [ 'bluegrass', 'chill' ,null ],
    [ 'blues', 'party' ,null ],
    [ 'bossanova','rock' ,null ],
    [ 'brazil', 'party' ,null ],
    [ 'breakbeat', 'electronic' , null ],
    [ 'british', 'country' , null ],
    [ 'cantopop', 'pop' ,null ],
    [ 'chicago-house', 'party' ,null ],
    [ 'children', 'chill' ,null ],
    [ 'chill', 'chill' ,null ],
    [ 'classical', 'classical' ,null ],
    [ 'club', 'party' ,null ],
    [ 'comedy', 'chill' ,null ],
    [ 'country', 'country',null ],
    [ 'dance', 'electronic' ,null ],
    [ 'dancehall', 'jazz' ,null ],
    [ 'death-metal', 'metal' ,null ],
    [ 'deep-house', 'party' ,null ],
    [ 'detroit-techno', 'electronic',null ],
    [ 'disco', 'party' ,null ],
    [ 'disney', 'chill' ,null ],
    [ 'drum-and-bass', 'rock' ,null ],
    [ 'dub', 'electronic' ,null ],
    [ 'dubstep', 'electronic' ,null ],
    [ 'edm', 'electronic' ,null ],
    [ 'electro', 'electronic' , null ],
    [ 'electronic', 'electronic'  ,null ],
    [ 'emo', 'romance' ,null ],
    [ 'folk', 'country' ,null ],
    [ 'forro', 'chill' ,null ],
    [ 'french', 'chill' ,null ],
    [ 'funk', 'punk' ,null ],
    [ 'garage', 'rock' ,null ],
    [ 'german', 'electronic',null ],
    [ 'gospel', 'country' ,null ],
    [ 'goth', 'punk' ,null ],
    [ 'grindcore', 'rock' ,null ],
    [ 'groove', 'party' ,null ],
    [ 'grunge', 'party',null ],
    [ 'guitar', 'acoustic',null ],
    [ 'happy', 'chill' ,null ],
    [ 'hard-rock', 'rock' ,null ],
    [ 'hardcore', 'rock' ,null ],
    [ 'hardstyle', 'metal' ,null ],
    [ 'heavy-metal', 'metal' ,null ],
    [ 'hip-hop', 'hip-hop' ,null ],
    [ 'holidays', 'chill' ,null ],
    [ 'honky-tonk', 'chill' ,null ],
    [ 'house', 'party' ,null ],
    [ 'idm', 'party' ,null ],
    [ 'indian', 'indian' ,null ],
    [ 'indie', 'indie' ,null ],
    [ 'indie-pop', 'pop' ,null ],
    [ 'industrial', 'metal' ,null ],
    [ 'iranian', 'party' ,null ],
    [ 'j-dance', 'k-pop' ,null ],
    [ 'j-idol', 'k-pop',null ],
    [ 'j-pop', 'k-pop' ,null ],
    [ 'j-rock', 'k-pop' ,null ],
    [ 'jazz', 'jazz' ,null ],
    [ 'k-pop', 'k-pop' ,null ],
    [ 'kids', 'chill' ,null ],
    [ 'latin', 'party' ,null ],
    [ 'latino', 'party' ,null ],
    [ 'malay', 'chill' ,null ],
    [ 'mandopop', 'pop' ,null ],
    [ 'metal', 'metal' ,null ],
    [ 'metal-misc', 'metal',null ],
    [ 'metalcore', 'metal' ,null ],
    [ 'minimal-techno', 'electronic' ,null ],
    [ 'movies', 'pop' ,null ],
    [ 'mpb', 'electronic' ,null ],
    [ 'new-age', 'rock' ,null ],
    [ 'new-release', 'pop' ,null ],
    [ 'opera', 'chill' ,null ],
    [ 'pagode', 'party' ,null ],
    [ 'party', 'party' ,null ],
    [ 'philippines-opm', 'party',null ],
    [ 'piano', 'acoustic' ,null ],
    [ 'pop', 'pop' ,null ],
    [ 'pop-film', 'pop' ,null ],
    [ 'post-dubstep', 'electronic' ,null ],
    [ 'power-pop', 'pop' ,null ],
    [ 'progressive-house', 'party' ,null ],
    [ 'psych-rock', 'rock' ,null ],
    [ 'punk', 'punk' ,null ],
    [ 'punk-rock', 'rock' ,null ],
    [ 'r-n-b', 'jazz' ,null ],
    [ 'rainy-day', 'chill' ,null ],
    [ 'reggae', 'jazz' ,null ],
    [ 'reggaeton', 'jazz' ,null ],
    [ 'road-trip', 'chill' ,null ],
    [ 'rock', 'rock' ,null ],
    [ 'rock-n-roll', 'rock' ,null ],
    [ 'rockabilly', 'rock' ,null ],
    [ 'romance', 'romance' ,null ],
    [ 'sad', 'romance' ,null ],
    [ 'salsa', 'party' ,null ],
    [ 'samba', 'party' ,null ],
    [ 'sertanejo', '' ,null ],
    [ 'show-tunes', 'pop' ,null ],
    [ 'singer-songwriter', 'acoustic' , null ],
    [ 'ska', '' ,null ],
    [ 'sleep', 'chill' ,null ],
    [ 'songwriter', 'acoustic' ,null ],
    [ 'soul', 'chill' ,null ],
    [ 'soundtracks', 'electronic' ,null ],
    [ 'spanish',  'party',null ],
    [ 'study', 'chill' ,null ],
    [ 'summer', 'pop' ,null ],
    [ 'swedish', 'party' ,null ],
    [ 'synth-pop', 'pop' ,null ],
    [ 'tango', 'party' ,null ],
    [ 'techno', 'electronic' ,null ],
    [ 'trance', 'party' ,null ],
    [ 'trip-hop', 'hip-hop' ,null ],
    [ 'turkish', 'party' ,null ],
    [ 'work-out', 'workout' ,null ],
    [ 'world-music', 'pop' ,null ]
]

module.exports = {categories , filteredCategories}